### PR TITLE
handle wiki links as obsidian urls

### PR DESCRIPTION
**Pull request by ttscoff**
This will need your review, but here's what I'm thinking:

- Convert wiki links to obsidian:// urls
- Handle `[]()` format links which Obsidian seems inclined to create nowadays

I'm using your existing root method to determine the vault name. I'm not a regular Obsidian user, so I don't know what pitfalls this might run into.

### CODE REVIEW

**Comment by voostindie** [comment]
To me this change would defeat the purpose of the filter a bit, because it rewrites links into new links, whereas the goal is to have documents _without_ such links. My own use case is that I used Marked with this filter to get a "clean" document that I can export into other formats, or copy-paste into e-mail. 

We could make it configurable though? Have a setting for it in the configuration file, and then either use the existing mode, or the Obsidian-URL mode?

On Obsidian links: Obsidian has a "Use [[Wikilinks]]" mode, which is enabled by default. If disabled it uses the traditional (and portable) []() format. See: <https://help.obsidian.md/Linking+notes+and+files/Internal+links>

I think you also squashed a few bugs in the regular expressions. Nice!

**Comment by ttscoff** [comment]
I'll add it as a config option. I think having the obsidian links option would be really useful to a lot of users. Alternatively, I can publish my own fork, but I like the idea of configurability.

**Comment by ttscoff** [comment]
New version pushed to this PR, all of my changes are now only enabled through config. Let me know if you don't want to incorporate this and I'll just publish as a new repo with credit linked back to here.

**Comment by voostindie** [comment]
I think there's a little bug hidden in line 48, but otherwise it looks good to me! 

I might want to refactor the code a bit to remove duplication, but that's not a big priority. I can do that later, after first adding some test cases. (Currently there are zero tests, but with more configurability there's also more complexity.) Like I said: that's for later.

I'm honored to accept a pull request from you; I know who you are! ;-)

**Comment by ttscoff** [comment]
One last commit that I saw before your last message, adds a marked_processor option (see commit notes).

Where is the bug you mentioned now that I've gone and messed up line numbering?

> I'm honored to accept a pull request from you; I know who you are! ;-)

Nice to meet you 😸

**Comment by ttscoff** [comment]
Never mind, I see it.

**Comment by voostindie** [comment]
Looks good!

**Pull request merged**
